/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.libs.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World kiwis!";
    }
}
